version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: server
    restart: unless-stopped
    ports:
      - "3000:3000"
    command: node index.js